### PR TITLE
Adding peter to the project

### PR DESCRIPTION
**Pull request by PeterBell**

### CODE REVIEW

**Comment by PeterBell** [comment]
I think every project is better with Peter :smile_cat:

**Comment by ghost** [comment]
:1234:

**Comment by geraldini** [comment]
:+1:

**Comment by sentei** [comment]
It's great! :+1:

**Comment by wallby74** [comment]
awesome

**Comment by soberano** [comment]
I'm speechless :octopus:

**Comment by PeterBell** [comment]
:+1:

**Comment by eneasz** [comment]
I agree :+1:

**Comment by mlaffey1971** [comment]
Looking good

**Comment by derheinz57** [comment]
Meh

**Comment by PeterBell** [comment]
LGTM (Looks Good To Me/Merge) :+1:

**Comment by PeterBell** [comment]
:-1:

**Comment by PeterBell** [comment]
Hey @derheinz57 what could I do to make this better and get your :+1: ?

**Comment by derheinz57** [comment]
@PeterBell Add some ketchup

**Comment by ghost** [comment]
Hey @wallby74

**Comment by PeterBell** [comment]
Hey @derheinz57 what do you think now?

**Comment by derheinz57** [comment]
@PeterBell awesome :+1:

**Comment by certify** [comment]
Hey, looks good to me - :+1: let's :ship: it

**Pull request merged**
